services:
  jellyfin:
    image: jellyfin/jellyfin:daily
    container_name: jellyfin
    user: 998:100
    group_add:
      - "106"
    restart: unless-stopped
    ports:
      - "8096:8096"
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - /tank/appdata/jellyfin/config:/config
      - /tank/appdata/jellyfin/cache:/cache
      - /tank/shared/nas-shared/torrents/completed/media:/media:ro
    devices:
      - /dev/dri:/dev/dri
    networks: [default, proxy]   # proxy = shared with caddy

networks:
  proxy:
    external: true
