version: '3.3'
services:
    transmission-openvpn:
        restart: always
        cap_add:
            - NET_ADMIN
        volumes:
            - '/tank/shared/nas-shared/torrents:/data'
            - '/tank/shared/nas-shared/transmission-config:/config'
        environment:
            - OPENVPN_PROVIDER=NORDVPN
            - OPENVPN_CONFIG=sweden
            - OPENVPN_USERNAME=
            - OPENVPN_PASSWORD=
            - LOCAL_NETWORK=192.168.0.0/16
            - PUID=998 
            - PGID=100 
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
